# Generated by Django 4.2.7 on 2025-11-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesteroffering',
            name='semester',
            field=models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2'), ('S3', 'Semester 3'), ('SS', 'Summer Session'), ('WS', 'Winter Session')], max_length=2),
        ),
    ]
