# Generated by Django 4.2.7 on 2025-11-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_semesteroffering_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='anti_requisites',
            field=models.ManyToManyField(blank=True, to='academic.unit'),
        ),
    ]
