# Generated by Django 4.2.7 on 2026-02-27 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0004_course_created_by_course_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_elective', models.BooleanField(default=False, help_text='If true, this unit is available as an elective to students of any major.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='academic.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='academic.unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course__code', 'unit__code'],
                'unique_together': {('course', 'unit')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='courses', through='academic.CourseUnit', to='academic.unit'),
        ),
    ]
