# Generated by Django 4.2.7 on 2025-11-25 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=20)),
                ('unit_name', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=2)),
                ('year', models.IntegerField()),
                ('credit_points', models.IntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ENROLLED', 'Enrolled'), ('WITHDRAWN', 'Withdrawn'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_entry', to='enrollment.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'semester', 'unit_code'],
                'indexes': [models.Index(fields=['student', '-year', 'semester'], name='enrollment__student_856251_idx'), models.Index(fields=['student', 'status'], name='enrollment__student_b1295a_idx')],
            },
        ),
    ]
