# Generated by Django 4.2.7 on 2025-11-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='generated_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='generation_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='generation_status',
            field=models.CharField(default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='last_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
