# Generated by Django 4.2.7 on 2026-03-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_targeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gcal_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID — set by n8n after creating the GCal event', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='generation_timeout_at',
            field=models.DateTimeField(blank=True, help_text='If generation_status stays pending past this datetime, treat as failed', null=True),
        ),
    ]
